### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Newbiedev39** [fasmat/homebrew-trader-workstation#32]
Hi,

I'd like to apologize in advanced for creating this issue - I was on [your site](https://about.me/matthias.fasching) and it said to contact you via the socials but none were linked except this Github.

I wanted to talk to regarding a [translation from Java to Go](https://stackoverflow.com/questions/13108567/migrate-java-decryption-code-to-golang) you helped with some years ago. I was looking to do something similar, but just wanted your input on it.

Is there anywhere else I'd be able to reach you?

**Comment by fasmat** [comment]
I'm available via the Gophers slack: https://join.slack.com/t/gophers/shared_invite/zt-proap3pu-ElK1vL6rGPTFlMu5GfLviA
